/**
 * Simple word/phrase blocklist for job title + description.
 * Keep this list small and explicit; add items as needed.
 */

const BLOCKED_WORDS = [
  // Add your words/phrases here (lower/upper doesn't matter)
  'drugs',
  'drvg',
  'drg',
  'drrugs',
  'druugs',
  'dr ugs',
  'dru gs',
  'narcotics',
  'cocaine',
  'c0caine',
  'coc4ine',
  'cocainee',
  'co caine',
  'coca ine',
  'heroin',
  'her0in',
  'herooin',
  'heronin',
  'he roin',
  'hero in',
  'meth',
  'm3th',
  'mth',
  'metth',
  'meeth',
  'methh',
  'm eth',
  'me th',
  'methamphetamine',
  'weed',
  'w33d',
  'weeed',
  'wead',
  'we ed',
  'wee d',
  'marijuana',
  'cannabis',
  'c4nnabis',
  'hash',
  'h4sh',
  'hashish',
  'opium',
  'fentanyl',
  'fent4nyl',
  'lsd',
  '1sd',
  'lsd d',
  'l sd',
  'acid',
  '4cid',
  'accid',
  'aciid',
  'ac id',
  'ecstasy',
  'mdma',
  'mdm4',
  'mdmma',
  'mdam',
  'md ma',
  'psychedelic',
  'shrooms',
  'shr00ms',
  'shroooms',
  'shrumz',
  'sh rooms',
  'shro oms',
  'magic mushrooms',
  'ketamine',
  'ket4mine',
  'crack',
  'smack',
  'dope',
  'd0pe',
  'substance',
  'contraband',
  'illegal substances',
  'pills',
  'xanax',
  'oxy',
  '0xy',
  'oxycodone',
  'percocet',
  'morphine',
  'codeine',
  'steroids',

  'kill',
  'k1ll',
  'ki11',
  'kiill',
  'killl',
  'kll',
  'k ill',
  'ki ll',
  'murder',
  'murd3r',
  'murderr',
  'murdr',
  'mur der',
  'murd er',
  'assassination',
  'hitman',
  'hitm4n',
  'hitmaan',
  'hitmn',
  'hit man',
  'execute',
  'slaughter',
  'stab',
  'st4b',
  'staab',
  'stabb',
  'st ab',
  'sta b',
  'shoot',
  'sh00t',
  'shoooot',
  'shoott',
  'sh oot',
  'sho ot',
  'gun down',
  'eliminate',
  'poison',
  'bomb',
  'b0mb',
  'bommb',
  'bombb',
  'bo mb',
  'bom b',
  'detonate',
  'attack',
  '4ttack',
  'assault',
  'harm',
  'injure',
  'violence',
  'torture',
  't0rture',
  'arson',
  'burn down',
  'destroy',
  'revenge attack',

  'kidnap',
  'k1dnap',
  'kidnapp',
  'kidnappp',
  'kid nap',
  'kidn ap',
  'kidnapping',
  'abduct',
  '4bduct',
  'abduuct',
  'abductt',
  'ab duct',
  'abdu ct',
  'abduction',
  'hostage',
  'h0stage',
  'hostaage',
  'hos tage',
  'host age',
  'human trafficking',
  'trafficking',
  'tr4fficking',
  'traffic',
  'traff1c',
  'trafffic',
  'tra ffic',
  'traf fic',
  'smuggling',
  'smuggle',
  'smugg1e',
  'illegal transport',
  'move goods illegally',
  'transport illegal',
  'black market delivery',
  'forced labor',
  'slave',
  'sl4ve',
  'slavery',

  'extort',
  '3xtort',
  'extortion',
  'blackmail',
  'bl4ckmail',
  'threaten',
  'threat',
  'thr34t',
  'ransom',
  'r4nsom',
  'demand money',
  'intimidation',
  'intimidate',
  'int1midate',
  'coercion',
  'force payment',
  'illegal collection',
  'harassment',

  'sex',
  's3x',
  'secks',
  'sxx',
  'sx',
  'seex',
  'seeex',
  'sexx',
  'seks',
  'saex',
  's ex',
  'sxx',
  'se x',
  'sexual',
  'escort',
  'esc0rt',
  'esccort',
  'escoort',
  'es cort',
  'esco rt',
  'prostitution',
  'porn',
  'p0rn',
  'pr0n',
  'po rn',
  'p orn',
  'poorn',
  'porrn',
  'p0orn',
  'pornography',
  'adult services',
  'adult',
  '4dult',
  'erotic',
  'nude',
  'n00d',
  'n00de',
  'nuude',
  'nudd',
  'nudz',
  'nu de',
  'nud e',
  'nudity',
  'naked',
  'n4ked',
  'naaked',
  'nakedd',
  'na ked',
  'nak ed',
  'onlyfans',
  'camgirl',
  'sexvideo',
  'xxx',
  'x x x',
  'xx x',
  'x xx',
  'hookup',
  'h00kup',
  'hookupp',
  'hukup',
  'hoookup',
  'ho okup',
  'hook up',
  'blowjob',
  'bl0wjob',
  'bloowjob',
  'blwjb',
  'bj',
  'b j',
  'bl owjob',
  'blow job',
  'fetish',
  'f3tish',
  'incest',
  'inc3st',
  'rape',
  'r4pe',
  'raape',
  'rappe',
  'ra pe',
  'rap e',
  'molest',
  'm0lest',
  'abuse',
  'sexual abuse',
  'minor',
  'underage',
  'child porn',
  'cp',

  'gun',
  'gvn',
  'firearm',
  'pistol',
  'p1stol',
  'rifle',
  'r1fle',
  'shotgun',
  'ammo',
  'amm0',
  'ammunition',
  'explosives',
  'grenade',
  'gren4de',
  'weapon',
  'weap0n',
  'knife attack',
  'silencer',
  'illegal weapon',
  'arms deal',

  'scam',
  'sc4m',
  'scaam',
  'scamm',
  'sc am',
  'sca m',
  'fraud',
  'fr4ud',
  'frraud',
  'fraudd',
  'fr aud',
  'fra ud',
  'money laundering',
  'fake documents',
  'identity theft',
  'phishing',
  'ph1shing',
  'phisshing',
  'phi shing',
  'phis hing',
  'hacking',
  'hack account',
  'hack',
  'h4ck',
  'haack',
  'hackk',
  'ha ck',
  'hac k',
  'hacker',
  'h4cker',
  'credit card fraud',
  'carding',
  'c4rding',
  'cardding',
  'car ding',
  'card ing',
  'darknet',
  'd4rknet',
  'ponzi',
  'illegal scheme',
  'cheat system',

  'illegal job',
  'illegal work',
  'shady work',
  'under the table illegal',
  'off the books illegal',
  'no questions asked',
  'no questions',
  'noquestion',
  'no asked',
  'noasked',
  'discreet illegal work',
  'discreet work',
  'discreetwork',
  'confidential illegal',
  'confidential task',
  'secret job',
  'secretjob',
  'urgent private job',
  'private job',
  'privatejob',
  'secret job',
  'risky job',
  'off the record',
  'off record',
  'offrecord',
  'under the table',
  'under table',
  'undertable',
  'cash only job',
  'cash job',
  'cashjob',
];

function normalizeText(s) {
  return String(s || '')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim();
}

function combinedText(title, description) {
  const t = normalizeText(title);
  const d = description != null ? normalizeText(description) : '';
  return `${t} ${d}`.trim();
}

/**
 * Checks if the combined title+description contains any blocked word/phrase.
 * @returns {{ blocked: boolean, match?: string }}
 */
function isJobTextBlockedByWords(title, description) {
  const haystack = combinedText(title, description);
  if (!haystack) return { blocked: false };

  for (const w of BLOCKED_WORDS) {
    const needle = normalizeText(w);
    if (!needle) continue;
    if (haystack.includes(needle)) {
      return { blocked: true, match: w };
    }
  }
  return { blocked: false };
}

module.exports = {
  BLOCKED_WORDS,
  isJobTextBlockedByWords,
};

