/**
 * Simple word/phrase blocklist for job title + description.
 * Keep this list small and explicit; add items as needed.
 */

const BLOCKED_WORDS = [
  // Add your words/phrases here (lower/upper doesn't matter)
  'drugs',
  'drvg',
  'drg',
  'drrugs',
  'druugs',
  'dr ugs',
  'dru gs',
  'narcotics',
  'cocaine',
  'c0caine',
  'coc4ine',
  'cocainee',
  'co caine',
  'coca ine',
  'heroin',
  'her0in',
  'herooin',
  'heronin',
  'he roin',
  'hero in',
  'meth',
  'm3th',
  'mth',
  'metth',
  'meeth',
  'methh',
  'm eth',
  'me th',
  'methamphetamine',
  'weed',
  'w33d',
  'weeed',
  'wead',
  'we ed',
  'wee d',
  'marijuana',
  'cannabis',
  'c4nnabis',
  'hash',
  'h4sh',
  'hashish',
  'opium',
  'fentanyl',
  'fent4nyl',
  'lsd',
  '1sd',
  'lsd d',
  'l sd',
  'acid',
  '4cid',
  'accid',
  'aciid',
  'ac id',
  'ecstasy',
  'mdma',
  'mdm4',
  'mdmma',
  'mdam',
  'md ma',
  'psychedelic',
  'shrooms',
  'shr00ms',
  'shroooms',
  'shrumz',
  'sh rooms',
  'shro oms',
  'magic mushrooms',
  'ketamine',
  'ket4mine',
  'crack',
  'smack',
  'dope',
  'd0pe',
  'substance',
  'contraband',
  'illegal substances',
  'pills',
  'xanax',
  'oxy',
  '0xy',
  'oxycodone',
  'percocet',
  'morphine',
  'codeine',
  'steroids',

  'kill',
  'k1ll',
  'ki11',
  'kiill',
  'killl',
  'kll',
  'k ill',
  'ki ll',
  'murder',
  'murd3r',
  'murderr',
  'murdr',
  'mur der',
  'murd er',
  'assassination',
  'hitman',
  'hitm4n',
  'hitmaan',
  'hitmn',
  'hit man',
  'execute',
  'slaughter',
  'stab',
  'st4b',
  'staab',
  'stabb',
  'st ab',
  'sta b',
  'shoot',
  'sh00t',
  'shoooot',
  'shoott',
  'sh oot',
  'sho ot',
  'gun down',
  'eliminate',
  'poison',
  'bomb',
  'b0mb',
  'bommb',
  'bombb',
  'bo mb',
  'bom b',
  'detonate',
  'attack',
  '4ttack',
  'assault',
  'harm',
  'injure',
  'violence',
  'torture',
  't0rture',
  'arson',
  'burn down',
  'destroy',
  'revenge attack',

  'kidnap',
  'k1dnap',
  'kidnapp',
  'kidnappp',
  'kid nap',
  'kidn ap',
  'kidnapping',
  'abduct',
  '4bduct',
  'abduuct',
  'abductt',
  'ab duct',
  'abdu ct',
  'abduction',
  'hostage',
  'h0stage',
  'hostaage',
  'hos tage',
  'host age',
  'human trafficking',
  'trafficking',
  'tr4fficking',
  'traffic',
  'traff1c',
  'trafffic',
  'tra ffic',
  'traf fic',
  'smuggling',
  'smuggle',
  'smugg1e',
  'illegal transport',
  'move goods illegally',
  'transport illegal',
  'black market delivery',
  'forced labor',
  'slave',
  'sl4ve',
  'slavery',

  'extort',
  '3xtort',
  'extortion',
  'blackmail',
  'bl4ckmail',
  'threaten',
  'threat',
  'thr34t',
  'ransom',
  'r4nsom',
  'demand money',
  'intimidation',
  'intimidate',
  'int1midate',
  'coercion',
  'force payment',
  'illegal collection',
  'harassment',

  'sex',
  's3x',
  'secks',
  'sxx',
  'sx',
  'seex',
  'seeex',
  'sexx',
  'seks',
  'saex',
  's ex',
  'sxx',
  'se x',
  'sexual',
  'escort',
  'esc0rt',
  'esccort',
  'escoort',
  'es cort',
  'esco rt',
  'prostitution',
  'porn',
  'p0rn',
  'pr0n',
  'po rn',
  'p orn',
  'poorn',
  'porrn',
  'p0orn',
  'pornography',
  'adult services',
  'adult',
  '4dult',
  'erotic',
  'nude',
  'n00d',
  'n00de',
  'nuude',
  'nudd',
  'nudz',
  'nu de',
  'nud e',
  'nudity',
  'naked',
  'n4ked',
  'naaked',
  'nakedd',
  'na ked',
  'nak ed',
  'onlyfans',
  'camgirl',
  'sexvideo',
  'xxx',
  'x x x',
  'xx x',
  'x xx',
  'hookup',
  'h00kup',
  'hookupp',
  'hukup',
  'hoookup',
  'ho okup',
  'hook up',
  'blowjob',
  'bl0wjob',
  'bloowjob',
  'blwjb',
  'bj',
  'b j',
  'bl owjob',
  'blow job',
  'fetish',
  'f3tish',
  'incest',
  'inc3st',
  'rape',
  'r4pe',
  'raape',
  'rappe',
  'ra pe',
  'rap e',
  'molest',
  'm0lest',
  'abuse',
  'sexual abuse',
  'minor',
  'underage',
  'child porn',
  'cp',

  'gun',
  'gvn',
  'firearm',
  'pistol',
  'p1stol',
  'rifle',
  'r1fle',
  'shotgun',
  'ammo',
  'amm0',
  'ammunition',
  'explosives',
  'grenade',
  'gren4de',
  'weapon',
  'weap0n',
  'knife attack',
  'silencer',
  'illegal weapon',
  'arms deal',

  'scam',
  'sc4m',
  'scaam',
  'scamm',
  'sc am',
  'sca m',
  'fraud',
  'fr4ud',
  'frraud',
  'fraudd',
  'fr aud',
  'fra ud',
  'money laundering',
  'fake documents',
  'identity theft',
  'phishing',
  'ph1shing',
  'phisshing',
  'phi shing',
  'phis hing',
  'hacking',
  'hack account',
  'hack',
  'h4ck',
  'haack',
  'hackk',
  'ha ck',
  'hac k',
  'hacker',
  'h4cker',
  'credit card fraud',
  'carding',
  'c4rding',
  'cardding',
  'car ding',
  'card ing',
  'darknet',
  'd4rknet',
  'ponzi',
  'illegal scheme',
  'cheat system',

  'illegal job',
  'illegal work',
  'shady work',
  'under the table illegal',
  'off the books illegal',
  'no questions asked',
  'no questions',
  'noquestion',
  'no asked',
  'noasked',
  'discreet illegal work',
  'discreet work',
  'discreetwork',
  'confidential illegal',
  'confidential task',
  'secret job',
  'secretjob',
  'urgent private job',
  'private job',
  'privatejob',
  'secret job',
  'risky job',
  'off the record',
  'off record',
  'offrecord',
  'under the table',
  'under table',
  'undertable',
  'cash only job',
  'cash job',
  'cashjob',

  // sex toys / adult items (EN + HI + obfuscations)
  'dildo',
  'd1ldo',
  'dilldo',
  'dildoo',
  'dil do',
  'डिल्डो',
  'vibrator',
  'v1brator',
  'vibraator',
  'vibrat0r',
  'vib rator',
  'वाइब्रेटर',
  'vibe',
  'v1be',
  'vibee',
  'buttplug',
  'buttpluug',
  'butt plug',
  'बट प्लग',
  'analtoy',
  'anal toy',
  'an4ltoy',
  'an altoy',
  'एनल टॉय',
  'sextoy',
  'sex toy',
  's3xtoy',
  's3x toy',
  'se xtoy',
  'सेक्स टॉय',
  'fleshlight',
  'fl3shlight',
  'fleshhlight',
  'फ्लेशलाइट',
  'masturbator',
  'm4sturbator',
  'masturbaator',
  'मास्टर्बेटर',
  'strapon',
  'straponn',
  'strap on',
  'str4pon',
  'स्ट्रैपऑन',
  'lube',
  'lubee',
  'l8be',
  'lu be',
  'ल्यूब',
  'condom',
  'condomm',
  'c0ndom',
  'कंडोम',

  // coercion / sexual violence (EN + HI + roman)
  'forced',
  'forc3d',
  'forceed',
  'for ced',
  'coerce',
  'c0erce',
  'coer ce',
  'exploit',
  'expl0it',
  'explo it',
  'बलात्कार',
  'balatkar',
  'छेड़छाड़',
  'chedchad',
  'chhed chhad',
  'यौन शोषण',
  'yaun shoshan',
  'दुराचार',
  'durachar',
  'जबरदस्ती',
  'zabardasti',
  'zabr dasti',
  'जबरन',
  'jabran',
  'शोषण',
  'shoshan',
  'गलत काम',
  'galat kaam',

  // weapons / restraint / explosives (EN + HI + roman)
  'guun',
  'g un',
  'बंदूक',
  'bandook',
  'पिस्तौल',
  'pist0l',
  'pis tol',
  'राइफल',
  'rifl e',
  'shot gu n',
  'bullet',
  'bull3t',
  'bulle t',
  'गोली',
  'goli',
  'कारतूस',
  'kartoos',
  'knife',
  'kn1fe',
  'kni fe',
  'चाकू',
  'chaku',
  'छुरी',
  'chhuri',
  'blade',
  'bl4de',
  'bla de',
  'ब्लेड',
  'बम',
  'bam',
  'explosive',
  'expl0sive',
  'explo sive',
  'विस्फोटक',
  'visphotak',
  'rope',
  'rop3',
  'roope',
  'ro pe',
  'रस्सी',
  'rassi',
  'chain',
  'ch4in',
  'chai n',
  'जंजीर',
  'zanjeer',
  'handcuff',
  'handcuffs',
  'h4ndcuff',
  'hand cuff',
  'हथकड़ी',
  'hathkadi',
  'tape',
  't4pe',
  'ta pe',
  'टेप',
  'blindfold',
  'bl1ndfold',
  'blind fold',
  'आंख पर पट्टी',
  'aankh patti',
  'gag',
  'g4g',
  'ga g',
  'मुंह बंद',
  'muh band',

  // smuggling / illegal delivery phrasing (EN + HI + roman)
  'cargo',
  'carg0',
  'car go',
  'package illegal',
  'illegal package',
  'transport illegal',
  'illegal transport',
  'smug gle',
  'container',
  'conta1ner',
  'cont ainer',
  'toy for adult',
  'adult toy',
  'private item',
  'secret item',
  'no questions item',
  'discreet delivery',
  'late night delivery',
  'cash delivery only',
  'hidden package',
  'तस्करी',
  'taskari',
  'गैरकानूनी माल',
  'gairkanuni maal',
  'अवैध सामान',
  'avaidh samaan',
  'छुपा हुआ पैकेज',
  'chhupa package',
  'कंटेनर',
  'डिलीवरी गुप्त',
  'gupt delivery',
  'कोई सवाल नहीं',
  'koi sawal nahi',
  'बिना सवाल',
  'bina sawal',
  'गुप्त काम',
  'gupt kaam',
  'सीक्रेट काम',
  'secret kaam',
  'प्राइवेट काम',
  'private kaam',
  'कैश में काम',
  'cash kaam',
  'अंडर टेबल',
  'रिकॉर्ड के बाहर',
];

function normalizeText(s) {
  return String(s || '')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim();
}

function hasTooManyRepeatedChars(s) {
  // Any character repeated 3+ times in a row => block (e.g. seeeeeex, hoooooookup, druuuuugs)
  return /(.)\1{2,}/.test(String(s || '').toLowerCase());
}

function combinedText(title, description) {
  const t = normalizeText(title);
  const d = description != null ? normalizeText(description) : '';
  return `${t} ${d}`.trim();
}

/**
 * Checks if the combined title+description contains any blocked word/phrase.
 * @returns {{ blocked: boolean, match?: string }}
 */
function isJobTextBlockedByWords(title, description) {
  if (hasTooManyRepeatedChars(title) || hasTooManyRepeatedChars(description)) {
    return { blocked: true, match: 'repeated_chars' };
  }

  const haystack = combinedText(title, description);
  if (!haystack) return { blocked: false };

  for (const w of BLOCKED_WORDS) {
    const needle = normalizeText(w);
    if (!needle) continue;
    if (haystack.includes(needle)) {
      return { blocked: true, match: w };
    }
  }
  return { blocked: false };
}

module.exports = {
  BLOCKED_WORDS,
  isJobTextBlockedByWords,
};

